---
- name: Certificate
  hosts: localhost

  vars:
    hostnames:
     - example.tld

  tasks:
    - name: Create CA private key
      community.crypto.openssl_privatekey:
        path: demo-ca-certificate.key

    - name: Create CA certificate signing request
      community.crypto.openssl_csr_pipe:
        privatekey_path: demo-ca-certificate.key
        common_name: Demo CA
        use_common_name_for_san: false
        basic_constraints:
          - 'CA:TRUE'
        basic_constraints_critical: true
        key_usage:
          - keyCertSign
        key_usage_critical: true
      register: ca_request

    - name: Create CA certificate
      community.crypto.x509_certificate:
        path: demo-ca-certificate.pem
        csr_content: "{{ ca_request.csr }}"
        privatekey_path: demo-ca-certificate.key
        provider: selfsigned

    - name: Create private key
      community.crypto.openssl_privatekey:
        path: "demo-{{ hostname }}.key"
      loop: "{{ hostnames }}"
      loop_control:
        loop_var: hostname

    - name: Create certificate signing request
      community.crypto.openssl_csr_pipe:
        privatekey_path: "demo-{{ hostname }}.key"
        common_name: "{{ hostname }}"
      register: requests
      loop: "{{ hostnames }}"
      loop_control:
        loop_var: hostname

    - name: Sign certificate with CA
      community.crypto.x509_certificate_pipe:
        csr_content: "{{ request.csr }}"
        provider: ownca
        ownca_path: demo-ca-certificate.pem
        ownca_privatekey_path: demo-ca-certificate.key
        ownca_not_after: +800d
        ownca_not_before: "-1d"
      register: certificates
      loop: "{{ requests.results }}"
      loop_control:
        label: "{{ request.hostname }}"
        loop_var: request

    - name: Create certificate
      copy:
        dest: "demo-{{ certificate.request.hostname }}.pem"
        content: "{{ certificate.certificate }}"
      loop: "{{ certificates.results }}"
      loop_control:
        label: "{{ certificate.request.hostname }}"
        loop_var: certificate
