---
- name: Test
  hosts: localhost

  roles:
    - chusiang.helloworld

  tasks:
    - name: ansible_role_names
      debug:
        msg: "{{ ansible_role_names }}"

    - command: echo $ANSIBLE_ROLES_PATH

    - command: ls -la /runner/requirements_roles
