---
- name: Collection Test
  hosts: localhost
  gather_facts: false

  roles:
    - my.collection.one
    - my.collection.two
    - my.collection.three

- name: Playbook
  ansible.builtin.import_playbook: my.collection.one
