---
- name: Collection Test
  hosts: localhost
  gather_facts: false

  roles:
    - my.collection.one
    - my.collection.two

  tasks:
    - name: Playbook
      ansible.builtin.import_playbook: my.collection.playbook
