---
- name: Test
  hosts: all
  gather_facts: false

  tasks:
    - name: Output env from group
      debug:
        msg: "{{ group_env }}"

    - name: Output env from inventory
      debug:
        msg: "{{ inventory_env }}"
